# Generated by Django 4.2.7 on 2023-11-24 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_rename_arrival_at_site_registration_arrival_at_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memento',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.invitee'),
        ),
    ]
