# Generated by Django 4.2.7 on 2023-11-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_memento_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='pm_dept',
            field=models.BooleanField(default=False),
        ),
    ]
