# Generated by Django 4.2.7 on 2023-11-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_invitee_pm_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
