# Generated by Django 4.2.7 on 2023-11-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_invitee_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invitee',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
